Class {
	#name : 'RowanSample9Class',
	#superclass : 'Object',
	#instVars : [
		'ivar0',
		'ivar1',
		'ivar2'
	],
	#category : 'RowanSample9-Core'
}

{ #category : 'accessing' }
RowanSample9Class >> ivar0 [ ^ ivar0
]

{ #category : 'accessing' }
RowanSample9Class >> ivar0: obj [ ivar0 := obj
]

{ #category : 'accessing' }
RowanSample9Class >> ivar1 [ ^ ivar1
]

{ #category : 'accessing' }
RowanSample9Class >> ivar1: obj [ ivar1 := obj
]

{ #category : 'accessing' }
RowanSample9Class >> ivar2 [ ^ ivar2
]

{ #category : 'accessing' }
RowanSample9Class >> ivar2: obj [ ivar2 := obj
]
