Class {
	#name : 'RowanSample9ClassC',
	#superclass : 'RowanSample9ClassA',
	#instVars : [
		'c',
		'ivar2'
	],
	#category : 'RowanSample9-Core'
}

{ #category : 'accessing' }
RowanSample9ClassC >> c [ ^ c
]

{ #category : 'accessing' }
RowanSample9ClassC >> c: obj [ c := obj
]

{ #category : 'accessing' }
RowanSample9ClassC >> ivar2 [ ^ ivar2
]

{ #category : 'accessing' }
RowanSample9ClassC >> ivar2: obj [ ivar2 := obj
]
