Class {
	#name : 'RowanSample9ClassA',
	#superclass : 'RowanSample9Class',
	#instVars : [
		'a',
		'ivar1'
	],
	#category : 'RowanSample9-Core'
}

{ #category : 'accessing' }
RowanSample9ClassA >> a [ ^ a
]

{ #category : 'accessing' }
RowanSample9ClassA >> a: obj [ a := obj
]

{ #category : 'accessing' }
RowanSample9ClassA >> ivar1 [ ^ ivar1
]

{ #category : 'accessing' }
RowanSample9ClassA >> ivar1: obj [ ivar1 := obj
]
