Class {
	#name : 'RowanSample9ClassF',
	#superclass : 'RowanSample9ClassB',
	#instVars : [
		'f',
		'ivar2'
	],
	#category : 'RowanSample9-Core'
}

{ #category : 'accessing' }
RowanSample9ClassF >> f [ ^ f
]

{ #category : 'accessing' }
RowanSample9ClassF >> f: obj [ f := obj
]

{ #category : 'accessing' }
RowanSample9ClassF >> ivar2 [ ^ ivar2
]

{ #category : 'accessing' }
RowanSample9ClassF >> ivar2: obj [ ivar2 := obj
]
