"
I am an example class
"
Class {
	#name : 'RowanSample9Class1',
	#superclass : 'Object',
	#instVars : [
		'ivar1'
	],
	#category : 'RowanSample9-Core'
}

{ #category : '*rowansample9-core' }
RowanSample9Class1 class >> bar1 [ ^1
]

{ #category : '*rowansample9-core' }
RowanSample9Class1 class >> bar2 [ ^2
]

{ #category : '*rowansample9-core' }
RowanSample9Class1 class >> bar3 [ ^3
]

{ #category : 'accessing' }
RowanSample9Class1 >> foo [ ^1
]

{ #category : '*rowansample9-core' }
RowanSample9Class1 >> foo2 [ ^2
]

{ #category : '*rowansample9-core' }
RowanSample9Class1 >> foo3 [ ^3
]
