Class {
	#name : 'RowanSample9ClassE',
	#superclass : 'RowanSample9ClassB',
	#instVars : [
		'e',
		'ivar2'
	],
	#category : 'RowanSample9-Core'
}

{ #category : 'accessing' }
RowanSample9ClassE >> e [ ^ e
]

{ #category : 'accessing' }
RowanSample9ClassE >> e: obj [ e := obj
]

{ #category : 'accessing' }
RowanSample9ClassE >> ivar2 [ ^ ivar2
]

{ #category : 'accessing' }
RowanSample9ClassE >> ivar2: obj [ ivar2 := obj
]
