Extension { #name : 'RowanSample9Class1' }

{ #category : '*rowansample9-extensions' }
RowanSample9Class1 class >> bar [ ^'bar'
]

{ #category : '*rowansample9-extensions' }
RowanSample9Class1 class >> bar4 [ ^4
]

{ #category : '*rowansample9-extensions' }
RowanSample9Class1 class >> bar5 [ ^5
]

{ #category : '*rowansample9-extensions' }
RowanSample9Class1 >> foo4 [ ^4
]

{ #category : '*rowansample9-extensions' }
RowanSample9Class1 >> foo5 [ ^5
]

{ #category : '*rowansample9-extensions' }
RowanSample9Class1 >> foo6 [ ^6
]
